name: monteage_employee
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  shared_preferences:
  get:
  flutter_screenutil:
  auto_size_text:
  get_storage:
  flutter_animate:
  font_awesome_flutter:
  google_fonts:
  path:
  path_provider:
  url_launcher:
  intl:
  image_picker:
  percent_indicator:
  pdf:
  printing:
  http:
  qr_flutter:
  geolocator:
  open_file:
  file_picker: 10.1.2
  permission_handler:
  share_plus:
  fl_chart:
  getx_super_snackbar:
  win32:
  logger:
  fluttertoast:
  provider:
  badges:
  flutter_file_downloader:
  youtube_player_flutter:
  flutter_calendar_carousel:
  search_page:
  custom_refresh_indicator:
  cached_network_image:
  extended_image:
  number_to_words:
  in_app_update:
  lottie:
  multi_select_flutter:
  dio:
  top_snackbar_flutter:
  vibration:
  timeago:
  geocoding:
  google_mlkit_face_detection:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^6.0.0

dependency_overrides:
  device_info_plus: 10.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/